# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: check-toml
  - id: end-of-file-fixer
  - id: double-quote-string-fixer

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.2.3
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --preserve-quotes
    - --indent=2

- repo: local
  hooks:
  - id: pycodestyle
    name: Format with Pycodestyle
    entry: pycodestyle
    language: system
    types: [python]

  - id: flake8
    name: Check with Flake8
    entry: flake8
    language: system
    types: [python]
