"""auto

Revision ID: 3fed96a3c316
Revises: 5959a5dd6c4c
Create Date: 2022-08-25 22:16:48.253441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fed96a3c316'
down_revision = '5959a5dd6c4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'PRODUCTS', ['NAME'])
    op.create_unique_constraint(None, 'PRODUCTS', ['ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'PRODUCTS', type_='unique')
    op.drop_constraint(None, 'PRODUCTS', type_='unique')
    # ### end Alembic commands ###
