"""auto

Revision ID: 5959a5dd6c4c
Revises: 819cbf6e030b
Create Date: 2022-08-21 23:39:57.376037

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5959a5dd6c4c'
down_revision = '819cbf6e030b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'PRODUCTS',
        sa.Column('ID', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            'CREATED',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'MODIFIED',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('NAME', sa.String(length=200), nullable=False),
        sa.Column('PRICE', sa.Integer(), nullable=False),
        sa.Column('STOCK_QUANTITY', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('ID'),
        sa.UniqueConstraint('ID'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PRODUCTS')
    # ### end Alembic commands ###
